### ISSUE TITLE
build fails in jdk 8

### ISSUE THREAD

**Issue by sreev** [prelert/engine-java#1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadocs) on project prelertEngineApiClient: MavenReportException: Error while creating archive:

I get this error when compiling with jdk 8 (1.80_51 oracle jdk).

**Comment by davidkyle** [comment]
Hi sreev thanks for your pull request I've merged it with master.

Great work thanks, there's a t shirt or some Prelert goodies on its way to you support will be in touch.
